#!/usr/bin/env python3
# Updates the user page on the website with the current user list

import cgi
import pwd
import os.path
import sys

users = 0

sys.stdout.write('USERS\n\n')
for user in sorted(pwd.getpwall(), key=lambda x: x.pw_name):
    # if the user doesn't have a public_html folder, skip
    if not os.path.exists(os.path.join(user.pw_dir, 'public_html')) or user.pw_gid != 100:
        continue

    # if .hidden exists in the public_html, skip it
    if os.path.exists(os.path.join(user.pw_dir, 'public_gopher', '.hidden')):
        continue

    gecos = ''
    if user.pw_gecos:
        gecos = ' - %s' % user.pw_gecos
    entry = "1~%s%s\t/~%s/\tdimension.sh\t70\n" % (user.pw_name, gecos, user.pw_name)
    users += 1
    sys.stdout.write(entry)

sys.stdout.write("\n\nTotal Users: %d\n" % users)
sys.stdout.write("\nUsers can be excluded from this list by creating a '.hidden' file in their\npublic_gopher.")
