#!/usr/bin/env python3
# Updates the user page on the website with the current user list
import sys
import json


def main(output=sys.stdout):
    output.write('USERS\n\n')

    with open('/var/www/dimension.sh/tilde.json', 'r') as fobj:
        data = json.loads(fobj.read())

    for user in data['users']:
        output.write("1~{username}\t/~{username}/\tdimension.sh\t70\n".format(**user))

    output.write("\n\nTotal Users: %d\n" % len(data['users']))
    output.write("\nUsers can be excluded from this list by creating a '.hidden' file in their public_html folder.")
    output.write("\r\n")


if __name__ == '__main__':
    main()
